services:
  - type: web
    name: invoices-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://op3nbv:xau_1yK7b5yd0gzUB5BZIbT1GOjqv1JogSGO0@us-east-1.sql.xata.sh/invoice-db:main?sslmode=require
      - key: JWT_SECRET
        value: patitos
      - key: CLOUDINARY_API_KEY
        value: 732617677476436
      - key: REDIS_URL
        value: redis:6379
  # - type: private
  #   name: redis
  #   image: redis:7
  #   dockerfilePath: ./Dockerfile.redis
  #   autoDeploy: false
